services:
  - type: web
    name: digital-librarian
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "22.5.0"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FINE_RATE_PER_DAY
        value: "5"
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: digital-librarian-db
          property: connectionString

databases:
  - name: digital-librarian-db
    databaseName: library_management_system
    user: librarian
    plan: free
    region: oregon
